### ISSUE TITLE
Unable to connect to ElasticSearch from host

### ISSUE THREAD

**Issue by wwhurley** [forumone/elasticsearch-formula#2]
After starting ElasticSearch on the guest, from the guest we get:

```
[vagrant@localhost ~]$ curl -I "http://localhost:9200"
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 0
```

From the host:

```
whurley-mac: whurley$ curl -I "http://localhost:9200"
curl: (52) Empty reply from server
```

The port is mapped by Vagrant

```
    default: 9200 (guest) => 9200 (host) (adapter 1)
```

**Comment by wwhurley** [comment]
The `elasticsearch.yml` file needs `network.bind_host: 0.0.0.0`

**Comment by mshade** [comment]
Added that parameter in commit 028fe1f

**Comment by wwhurley** [comment]
I'm not seeing either the cors attribute or the network.bind_host attribute in `/etc/elasticsearch/elasticsearch.yml` on a fresh installation.

**Comment by wwhurley** [comment]
Actually, NM. On the core project it's showing, though it wasn't on one where I copied things over to it. So it's project specific.
